name: "setup poetry and python"
description: "Setup python, poetry, and development environment"
inputs:
  type:
    description: "Type of the venv to create"
    required: true
  python-version:
    description: "Python version to use"
    required: true
  poetry-version:
    description: "Poetry version to use"
    required: true

runs:
  using: "composite"
  steps:
      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-v2-${{ inputs.type }}-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Cache pre-commit
        id: cache-pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-v2-${{ inputs.type }}-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Cache setup-poetry
        id: cache-setup-poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/pypoetry
            ~/.local/share/virtualenv
            ~/.local/bin/poetry
          key: setup-poetry-v2-${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.poetry-version }}

      - name: Setup python
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ inputs.python-version }}

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v8
        id: setup_poetry
        if: steps.cache-setup-poetry.outputs.cache-hit != 'true'
        with:
          poetry-version: ${{ inputs.poetry-version }}

      - name: Bootstrap environment
        shell: bash
        run: |
          make dev EXTRAS=${{ inputs.type }}
